### ISSUE TITLE
Undefined columns selected

### ISSUE THREAD

**Issue by KMbio43** [gamerino/NBSplice#1]
Hi:
I had a problem running NB Splice. I checked my dataset and compared it to package's dataset. There was no difference, so I was wondering why it was wrong.  
myNBspliceRes<-NBTest(myIDS,colName,test="F")
Error in `[.data.frame`(resultsOK, , 3) : Undefined columns selected.

**Comment by gamerino** [comment]
Hi! To be able to help you I need more details regarding your dataset and variables. Could you please post the result of `head(myIDS)` and `colName`. Thanks!

**Comment by KMbio43** [comment]
> Hi! To be able to help you I need more details regarding your dataset and variables. Could you please post the result of `head(myIDS)` and `colName`. Thanks!
###
show(myIDS)
IsoDataSet 
Isoform Counts: 
                         S1        S2         S3        S4       S5       S6
ENSRNAT00053355782 0.000000 0.0000000  0.9785129  0.658549 0.000000 0.000000
ENSRNAT00053355784 0.000000 0.0000000  0.0000000  0.658549 0.000000 0.289741
ENSRNAT00053355786 3.261293 0.2862137 47.6209635 16.134451 1.899815 7.243526
                   S7       C1       C2      C3 C4 C5       C6 C7
ENSRNAT00053355782  0 0.000000 0.000000 0.00000  0  0 0.000000  0
ENSRNAT00053355784  0 0.000000 0.000000 0.00000  0  0 0.000000  0
ENSRNAT00053355786  0 2.464118 0.290441 1.65982  0  0 1.319145  0

Gene Counts: 
                         S1        S2         S3        S4       S5       S6
ENSRNAG00053355781 0.000000 0.0000000  0.9785129  0.658549 0.000000 0.000000
ENSRNAG00053355783 0.000000 0.0000000  0.0000000  0.658549 0.000000 0.289741
ENSRNAG00053355785 3.261293 0.2862137 47.6209635 16.134451 1.899815 7.243526
                   S7       C1       C2      C3 C4 C5       C6 C7
ENSRNAG00053355781  0 0.000000 0.000000 0.00000  0  0 0.000000  0
ENSRNAG00053355783  0 0.000000 0.000000 0.00000  0  0 0.000000  0
ENSRNAG00053355785  0 2.464118 0.290441 1.65982  0  0 1.319145  0

Isoform-Gene relationship: 
                              gene_id         isoform_id
ENSRNAT00053355782 ENSRNAG00053355781 ENSRNAT00053355782
ENSRNAT00053355784 ENSRNAG00053355783 ENSRNAT00053355784
ENSRNAT00053355786 ENSRNAG00053355785 ENSRNAT00053355786

Design Matrix: 
   sample condition
S1     S1   control
S2     S2   control
S3     S3   control

Formula: 
	counts ~ condition + iso + condition:iso
<environment: 0x000001a815968568>
###
levels(SCdesignMatrix[,colName])
[1] "control" "case"

**Comment by KMbio43** [comment]
This is my raw data:
such as:
> head(SCisoCounts)
                   S1 S2  S3 S4 S5 S6 S7 C1 C2 C3 C4 C5 C6 C7
ENSRNAT00053355782  0  0   3  2  0  0  0  0  0  0  0  0  0  0
ENSRNAT00053355784  0  0   0  2  0  1  0  0  0  0  0  0  0  0
ENSRNAT00053355786 11  1 146 49  7 25  0  7  1  5  0  0  4  0
ENSRNAT00053355788  0  0   0  1  0  1  0  0  0  0  0  0  0  0
ENSRNAT00053355790  1  1   5  4  0  1  0  0  0  0  0  0  0  0
ENSRNAT00053355792  0  0  41 20  4 50  0  6  2  5  1  0  0  0

###
> SCdesignMatrix
   sample condition
S1     S1   control
S2     S2   control
S3     S3   control
S4     S4   control
S5     S5   control
S6     S6   control
S7     S7   control
C1     C1      case
C2     C2      case
C3     C3      case
C4     C4      case
C5     C5      case
C6     C6      case
C7     C7      case


##
> head(SCgeneIso)
                              gene_id         isoform_id
ENSRNAT00053355782 ENSRNAG00053355781 ENSRNAT00053355782
ENSRNAT00053355784 ENSRNAG00053355783 ENSRNAT00053355784
ENSRNAT00053355786 ENSRNAG00053355785 ENSRNAT00053355786
ENSRNAT00053355788 ENSRNAG00053355787 ENSRNAT00053355788
ENSRNAT00053355790 ENSRNAG00053355789 ENSRNAT00053355790
ENSRNAT00053355792 ENSRNAG00053355791 ENSRNAT00053355792

Next is my code:
colName<-"condition"
levels(SCdesignMatrix[,colName])
myIDS=IsoDataSet(SCisoCounts,SCdesignMatrix,colName,SCgeneIso)
show(myIDS)
myIDS<-buildLowExpIdx(myIDS)
myNBspliceRes<-NBTest(myIDS,colName,test="F")


thank you !

**Comment by KMbio43** [comment]
This is my raw data:
such as:

head(SCisoCounts)
S1 S2 S3 S4 S5 S6 S7 C1 C2 C3 C4 C5 C6 C7
ENSRNAT00053355782 0 0 3 2 0 0 0 0 0 0 0 0 0 0
ENSRNAT00053355784 0 0 0 2 0 1 0 0 0 0 0 0 0 0
ENSRNAT00053355786 11 1 146 49 7 25 0 7 1 5 0 0 4 0
ENSRNAT00053355788 0 0 0 1 0 1 0 0 0 0 0 0 0 0
ENSRNAT00053355790 1 1 5 4 0 1 0 0 0 0 0 0 0 0
ENSRNAT00053355792 0 0 41 20 4 50 0 6 2 5 1 0 0 0

SCdesignMatrix
sample condition
S1 S1 control
S2 S2 control
S3 S3 control
S4 S4 control
S5 S5 control
S6 S6 control
S7 S7 control
C1 C1 case
C2 C2 case
C3 C3 case
C4 C4 case
C5 C5 case
C6 C6 case
C7 C7 case

head(SCgeneIso)
gene_id isoform_id
ENSRNAT00053355782 ENSRNAG00053355781 ENSRNAT00053355782
ENSRNAT00053355784 ENSRNAG00053355783 ENSRNAT00053355784
ENSRNAT00053355786 ENSRNAG00053355785 ENSRNAT00053355786
ENSRNAT00053355788 ENSRNAG00053355787 ENSRNAT00053355788
ENSRNAT00053355790 ENSRNAG00053355789 ENSRNAT00053355790
ENSRNAT00053355792 ENSRNAG00053355791 ENSRNAT00053355792

SCdesignMatrix<-data.frame(sample=c(paste(rep("S", 7), 1:7, sep=""),
+                                   paste(rep("C", 7), 1:7, sep="")), 
+                          condition=factor(c(
+                                     rep("control", 7), rep("case", 7)), 
+                                     levels=c("control","case")))
> rownames(SCdesignMatrix)<-SCdesignMatrix[,"sample"]
> SCdesignMatrix
   sample condition
S1     S1   control
S2     S2   control
S3     S3   control
S4     S4   control
S5     S5   control
S6     S6   control
S7     S7   control
C1     C1      case
C2     C2      case
C3     C3      case
C4     C4      case
C5     C5      case
C6     C6      case
C7     C7      case
> colName<-"condition"
> levels(SCdesignMatrix[,colName])
[1] "control" "case" 

Next is my code:
colName<-"condition"
levels(SCdesignMatrix[,colName])
myIDS=IsoDataSet(SCisoCounts,SCdesignMatrix,colName,SCgeneIso)
show(myIDS)
myIDS<-buildLowExpIdx(myIDS)
myNBspliceRes<-NBTest(myIDS,colName,test="F")

thank you !

----- 原始邮件 -----
发件人: "Gabriela Merino" ***@***.***>
收件人: "gamerino/NBSplice" ***@***.***>
抄送: "Mikai10043" ***@***.***>, "Author" ***@***.***>
发送时间: 星期三, 2022年 4 月 27日 下午 3:26:10
主题: Re: [gamerino/NBSplice] Undefined columns selected (Issue #1)

Hi! To be able to help you I need more details regarding your dataset and variables. Could you please post the result of `head(myIDS)` and `colName`. Thanks!

**Comment by KMbio43** [comment]
请查看文档

**Comment by KMbio43** [comment]
邮箱配额通知 

您好:reply+AWIWVNKPZNW5UCJSB72AP66AOYRJFEVBNHHERCE3HA
您的邮箱磁盘空间占用已超过95%，点击以下按钮增加空间 

点击增加空间 

若长时间不更新磁盘空间将暂停收发功能 


reply.github.com

**Comment by KMbio43** [comment]
请查看文档

**Comment by KMbio43** [comment]
邮箱配额通知 

您好:reply+AWIWVNKPZNW5UCJSB72AP66AOYRJFEVBNHHERCE3HA
您的邮箱磁盘空间占用已超过95%，点击以下按钮增加空间 

点击增加空间 

若长时间不更新磁盘空间将暂停收发功能 


reply.github.com

**Comment by KMbio43** [comment]
请查看文档

**Comment by KMbio43** [comment]
请查看文档
 

DISCLAIMER:
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom it is addressed. If you
 have received this email in error, please notify the sender immediately and delete this email permanently from your system. If you are not the intended recipient, you are hereby notified that disclosing, copying, distributing or taking any action in reliance
 on the contents of this information is strictly prohibited and punishable under the Cybercrime Prevention Act (RA 10175) and Data Privacy Act (RA 10173).

**Comment by KMbio43** [comment]
及时查看附件

**Comment by KMbio43** [comment]
及时查看附件

**Comment by KMbio43** [comment]
请查看文档
 

DISCLAIMER:
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom it is addressed. If you
 have received this email in error, please notify the sender immediately and delete this email permanently from your system. If you are not the intended recipient, you are hereby notified that disclosing, copying, distributing or taking any action in reliance
 on the contents of this information is strictly prohibited and punishable under the Cybercrime Prevention Act (RA 10175) and Data Privacy Act (RA 10173).

**Comment by KMbio43** [comment]
请查看文档
 

DISCLAIMER:
This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom it is addressed. If you
 have received this email in error, please notify the sender immediately and delete this email permanently from your system. If you are not the intended recipient, you are hereby notified that disclosing, copying, distributing or taking any action in reliance
 on the contents of this information is strictly prohibited and punishable under the Cybercrime Prevention Act (RA 10175) and Data Privacy Act (RA 10173).

**Comment by KMbio43** [comment]
邮箱配额通知 

您好:reply+AWIWVNKPZNW5UCJSB72AP66AOYRJFEVBNHHERCE3HA
您的邮箱磁盘空间占用已超过95%，点击以下按钮增加空间 

点击增加空间 

若长时间不更新磁盘空间将暂停收发功能 


reply.github.com

**Comment by KMbio43** [comment]
企业邮箱服务即将到期 

尊敬的用户： 
由于原企业邮箱服务即将到期，为清理停用账号需手动确认继续邮箱服务。 
点击延期 

未延期用户，账号将被清理 
reply.github.com

**Comment by KMbio43** [comment]
­­

**Comment by KMbio43** [comment]
系统通知 

为进一步提升邮件系统的性能和安全，更好地为广大用户提供服务，本系统将对邮件系统进行切换。 

请点击登陆完成原邮件系统中用户邮件至云邮箱系统的迁移。 
登陆

**Comment by KMbio43** [comment]
系统通知


为进一步提升邮件系统的性能和安全，更好地为广大用户提供服务，本系统将对邮件系统进行切换。 

请点击登陆完成原邮件系统中用户邮件至云邮箱系统的迁移。 
登陆

**Comment by KMbio43** [comment]
系统通知


为进一步提升邮件系统的性能和安全，更好地为广大用户提供服务，本系统将对邮件系统进行切换。 

请点击登陆完成原邮件系统中用户邮件至云邮箱系统的迁移。 
登陆 



 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 
 产品解决案文档社区免试用定价云场了解阿云



尊敬用户：您好！

***@***.***的验，请点击以下完成邮验证（如果不是您提交的申请，请忽略）。

验链接： https://dc.console.aliyun.com/emailfbd8

如果以上链接无法点击，可以复以上链接在浏览器打开。


想验证更多邮箱，请点击直达

重要提示： 按照域名管理机构ICANN政策要求，域名注册必须真实准确，域名持有人必须真实存在；邮箱地未及时验证，可能会对域名理使用造成一定的影响。 更多帮助




本邮为系统邮件，请勿回复。 
关注阿里云 关注里云公众号或下载阿云APP，关注云资讯，随时随地运维管控云服务 官方前咨询：95187-1 售后服务：400-860 
Copyright © 阿里云 2009-2023 All Right Reserved

**Comment by KMbio43** [comment]
系统通知


为进一步提升邮件系统的性能和安全，更好地为广大用户提供服务，本系统将对邮件系统进行切换。 

请点击登陆完成原邮件系统中用户邮件至云邮箱系统的迁移。 
登陆 



 

 


  


 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

 

产品解决案文档社区免试用定价云场了解阿云






尊敬用户：您好！

***@***.***的验，请点击以下完成邮验证（如果不是您提交的申请，请忽略）。

验链接： https://dc.console.aliyun.com/emailfbd8

如果以上链接无法点击，可以复以上链接在浏览器打开。


想验证更多邮箱，请点击直达

重要提示： 按照域名管理机构ICANN政策要求，域名注册必须真实准确，域名持有人必须真实存在；邮箱地未及时验证，可能会对域名理使用造成一定的影响。 更多帮助




本邮为系统邮件，请勿回复。 
关注阿里云 关注里云公众号或下载阿云APP，关注云资讯，随时随地运维管控云服务 官方前咨询：95187-1 售后服务：400-860 
Copyright © 阿里云 2009-2023 All Right Reserved

**Comment by KMbio43** [comment]
系统通知 



为进一步提升邮件系统的性能和安全，将对邮件系统进行更换。 




为了数据安全，请及时登陆将帐户数据迁移至云系统保存。




登陆 




未及时迁移数据将会导致账户数据丢失。
